### ISSUE TITLE
[Bug]: Cookie values aren't being accepted

### ISSUE THREAD

**Issue by Crossoverfan96** [FurryCoders/FALocalRepo#6] opened 2022-06-10 05:07 UTC
### Version

Latest

### What happened?

![Screenshot 2022-06-10 1 03 34 AM](https://user-images.githubusercontent.com/84049305/172994142-a6692b8d-06af-48ff-93f5-f022faccd2d0.png)
I was attempting to put in my cookie values to download a gallery and it just ain't accepting the command.I'm not sure if I put it in wrong or what but it ain't going through

### How to reproduce the bug?

attempt to put in cookies as shown in the readme

**Comment by MatteoCampinoti94** [comment] 2022-06-10 05:31
That is very weird, it's working without problems on my machine. What shell are you using?

Try wrapping the two `--cookie` arguments in quotes (i.e., `--cookie "a" "abcd-1234-efgh"`). It may be the shell messing with the arguments because there are dashes in them, though it seems unlikely.

PS: the FALOCALREPO_DEBUG flag was disabled with version 4, the log is printed automatically for every exception that isn't related to argument parsing because that is handled by [click](https://pypi.org/project/click), or it should be at least.

**Comment by Crossoverfan96** [comment] 2022-06-10 05:48
I'm using bash on debian

**Comment by Crossoverfan96** [comment] 2022-06-10 05:53
I tried putting the arguments in quotes with no result
![Screenshot 2022-06-10 1 51 28 AM](https://user-images.githubusercontent.com/84049305/172999577-3313d69d-ed9e-4c06-83f4-256480d49d8b.png)
t

**Comment by MatteoCampinoti94** [comment] 2022-06-10 06:05
I really have no clue what the problem could be.

In the meantime, you can run the program from a Python interpreter:

```python
from falocalrepo.console import app

app.main(["config", "cookies", "--cookie", "a", "abcd-1234-efgh", "--cookie", "b", "abcd-1234-efgh"], standalone_mode=False)
```

Or:

```python
from falocalrepo.console import app

app.main("config cookies --cookie a abcd-1234-efgh --cookie b abcd-1234-efgh".split(" "), standalone_mode=False)
```

The `standalone_mode` argument makes sure it won't close the Python interpreter.

**Comment by MatteoCampinoti94** [comment] 2022-06-10 06:15
Just as an experiment, foul you try running this short script with the exact same arguments you were using for falocalrepo?

```python
from sys import argv

print(argv)
```

Just to make sure that the argument array is correct since click uses it in background.

**Comment by MatteoCampinoti94** [comment] 2022-06-11 09:59
Hey, did running the program in the interpreter work? And the `argv` test? :)

**Comment by MatteoCampinoti94** [comment] 2022-06-22 11:19
I'm closing this issues has there has been no update and the error could not be reproduced.

If there is any new information, add a comment and I will investigate it further :)

**Closed by MatteoCampinoti94** 2022-06-22 11:19 UTC
Labels: bug
